const mongoose = require("mongoose");

const OrderSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
            ref: 'User',
        },
        products: [
            {
                product: {
                    type: mongoose.Schema.Types.ObjectId,
                    required: true,
                    ref: 'Product',
                },
                quantity: {
                    type: Number,
                    required: true,
                },
                total_price: {
                    type: Number,
                    required: true,
                },
            },
        ],
        status: {
            type: String,
            enum: ['Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'],
            default: 'Pending',
        },
        shippingAddress: {
            type: String,
            required: true,
        },
        shippingCity: {
            type: String,
            required: true,
        },
        shippingZip: {
            type: String,
            required: true,
        },
        shippingCountry: {
            type: String,
            required: true,
        },
        paymentMethod: {
            type: String,
            required: true,
        },
        payment_id: {
            type: String,
            required: [
                true,
                "Please Provide the Payment ID generated by the server",
            ],
        },
        signature: {
            type: String,
            required: [
                true,
                "Please Provide the signature generated by the server",
            ],
        },
        createdAt: {
            type: Date,
            default: Date.now,
        },
    }
);

module.exports = mongoose.model('Order', OrderSchema);